### ISSUE TITLE
换成python3 环境 

### ISSUE THREAD

**Issue by YuanCoder** [lingochamp/tensorflow-dkt#1]
您好是这样的 我换成python3的环境去执行  在data_process.py 中的  seq_len = np.array(map(lambda seq: len(seq), seqs_in)) - 1  这段代码报错，没看明白，np.array 数组减1 ？

assistments.txt 里 一行的顺序先对应学生id  题目id  问题的对错吗？

**Comment by jinxulin** [comment]
@YuanCoder 
1.  因为数据是各个时刻 t_0 ~ t_n 的题目id, 答题对错。 而dkt模型任意时刻 t_k 的输入是 t_{k-1} 时刻的题目id答题对错，输出是 t_k 时刻所有题目的答题对错。 所以输入要扔掉最后一条，输出要扔掉第一条，seq_len 要减一 
2. assistments.txt 格式是学生id，题目id，问题对错

**Comment by YuanCoder** [comment]
好的  谢谢您的解答，最近也在研究知识追踪这一块，向您学习 @jinxulin
